# Tema 1 - Matrices

Vamos a ver cómo crear una matriz utilzando la librería `numpy`.

## Modo clásico

In [3]:
row = [1,2,3]
row

[1, 2, 3]

In [4]:
col = [[1], [2], [3]]
col

[[1], [2], [3]]

In [5]:
M = [[1,2,3], [4,5,6], [7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
M[1][1] #El primer corchete es la fila y el segundo es la columna

5

In [9]:
M[0][0]

1

In [11]:
import numpy as np

In [20]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = float)

In [21]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [28]:
M[0] #Accedo a la primera fila

array([1., 2., 3.])

In [30]:
for row in M:
    print(row[0]) #Accedemos a la primer columna, debe hacerse forzosamente con un bucle.

1.0
4.0
7.0


## Operaciones con matrices

In [22]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0], [1,-1]])

In [23]:
A+B #Suma de matrices

array([[4, 2],
       [4, 3]])

In [24]:
A.dot(B) #Multiplicación de matrices

array([[ 5, -2],
       [13, -4]])

In [25]:
A.transpose() #Transpuesta de A

array([[1, 3],
       [2, 4]])

In [27]:
A.trace() #Suma de los elementos de la diagonal

5